### ISSUE TITLE
Does it works with PHP 7.0?

### ISSUE THREAD

**Issue by stavarengo** [fntlnz/cld2-php-ext#3]
Hi guys. I've been using this extension for almost a year with PHP 5.6.

Now we are ready to update all our scripts to PHP 7.0, and when we tried to compile cld2-php-ext with the new version of PHP, it fail with the messages bellow.

So, did I do something wrong or in fact it is not compatible with PHP >= 7.0??

```bash
/bin/bash /opt/cld2-php-ext/libtool --mode=compile g++  -I. -I/opt/cld2-php-ext -DPHP_ATOM_INC -I/opt/cld2-php-ext/include -I/opt/cld2-php-ext/main -I/opt/cld2-php-ext -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/opt/cld2-php-ext/libcld2  -DHAVE_CONFIG_H  -g -O2   -c /opt/cld2-php-ext/cld2.cc -o cld2.lo 
libtool: compile:  g++ -I. -I/opt/cld2-php-ext -DPHP_ATOM_INC -I/opt/cld2-php-ext/include -I/opt/cld2-php-ext/main -I/opt/cld2-php-ext -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/opt/cld2-php-ext/libcld2 -DHAVE_CONFIG_H -g -O2 -c /opt/cld2-php-ext/cld2.cc  -fPIC -DPIC -o .libs/cld2.o
/opt/cld2-php-ext/cld2.cc:124:72: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
     add_assoc_string(return_value, "language_code", dl.language_code, 1);
                                                                        ^
/opt/cld2-php-ext/cld2.cc:125:72: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
     add_assoc_string(return_value, "language_name", dl.language_name, 1);
                                                                        ^
/opt/cld2-php-ext/cld2.cc:283:68: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
         RETURN_STRING(CLD2::LanguageName(CLD2::UNKNOWN_LANGUAGE), 1);
                                                                    ^
/opt/cld2-php-ext/cld2.cc:287:43: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
     RETURN_STRING(CLD2::LanguageName(l), 1);
                                           ^
/opt/cld2-php-ext/cld2.cc:302:68: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
         RETURN_STRING(CLD2::LanguageCode(CLD2::UNKNOWN_LANGUAGE), 1);
                                                                    ^
/opt/cld2-php-ext/cld2.cc:305:43: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
     RETURN_STRING(CLD2::LanguageCode(l), 1);
                                           ^
/opt/cld2-php-ext/cld2.cc:347:64: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
        RETURN_STRING(encodingStrings[CLD2::UNKNOWN_ENCODING], 1);
                                                                ^
/opt/cld2-php-ext/cld2.cc:350:47: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
     RETURN_STRING(encodingStrings[encoding], 1);
                                               ^
/opt/cld2-php-ext/cld2.cc: In function ‘void zim_cld2_detector_detect(zend_execute_data*, zval*)’:
/opt/cld2-php-ext/cld2.cc:113:116: error: too few arguments to function ‘zval* zend_read_property(zend_class_entry*, zval*, const char*, size_t, zend_bool, zval*)’
     is_plain = zend_read_property(cld2_detector_ce, detector, "isPlainText", sizeof("isPlainText") - 1, 1 TSRMLS_CC);
                                                                                                                    ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /opt/cld2-php-ext/php_cld2.h:12,
                 from /opt/cld2-php-ext/cld2.cc:1:
/usr/include/php/20151012/Zend/zend_API.h:356:16: note: declared here
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zval *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^
/opt/cld2-php-ext/cld2.cc:114:108: error: too few arguments to function ‘zval* zend_read_property(zend_class_entry*, zval*, const char*, size_t, zend_bool, zval*)’
     tld_hint = zend_read_property(cld2_detector_ce, detector, "tldHint", sizeof("tldHint") - 1, 1 TSRMLS_CC);
                                                                                                            ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /opt/cld2-php-ext/php_cld2.h:12,
                 from /opt/cld2-php-ext/cld2.cc:1:
/usr/include/php/20151012/Zend/zend_API.h:356:16: note: declared here
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zval *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^
/opt/cld2-php-ext/cld2.cc:115:123: error: too few arguments to function ‘zval* zend_read_property(zend_class_entry*, zval*, const char*, size_t, zend_bool, zval*)’
     language_hint = zend_read_property(cld2_detector_ce, detector, "languageHint", sizeof("languageHint") - 1, 1 TSRMLS_CC);
                                                                                                                           ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /opt/cld2-php-ext/php_cld2.h:12,
                 from /opt/cld2-php-ext/cld2.cc:1:
/usr/include/php/20151012/Zend/zend_API.h:356:16: note: declared here
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zval *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^
/opt/cld2-php-ext/cld2.cc:116:123: error: too few arguments to function ‘zval* zend_read_property(zend_class_entry*, zval*, const char*, size_t, zend_bool, zval*)’
     encoding_hint = zend_read_property(cld2_detector_ce, detector, "encodingHint", sizeof("encodingHint") - 1, 1 TSRMLS_CC);
                                                                                                                           ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /opt/cld2-php-ext/php_cld2.h:12,
                 from /opt/cld2-php-ext/cld2.cc:1:
/usr/include/php/20151012/Zend/zend_API.h:356:16: note: declared here
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zval *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^
/opt/cld2-php-ext/cld2.cc:124:5: error: ‘add_assoc_string’ was not declared in this scope
     add_assoc_string(return_value, "language_code", dl.language_code, 1);
     ^
/opt/cld2-php-ext/cld2.cc: In function ‘void zim_cld2_detector_isPlainText(zend_execute_data*, zval*)’:
/opt/cld2-php-ext/cld2.cc:139:115: error: too few arguments to function ‘zval* zend_read_property(zend_class_entry*, zval*, const char*, size_t, zend_bool, zval*)’
     is_plain = zend_read_property(cld2_detector_ce, detector, "isPlainText", sizeof("isPlainText") -1, 1 TSRMLS_CC);
                                                                                                                   ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /opt/cld2-php-ext/php_cld2.h:12,
                 from /opt/cld2-php-ext/cld2.cc:1:
/usr/include/php/20151012/Zend/zend_API.h:356:16: note: declared here
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zval *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^
/opt/cld2-php-ext/cld2.cc: In function ‘void zim_cld2_detector_getTldHint(zend_execute_data*, zval*)’:
/opt/cld2-php-ext/cld2.cc:166:108: error: too few arguments to function ‘zval* zend_read_property(zend_class_entry*, zval*, const char*, size_t, zend_bool, zval*)’
     tld_hint = zend_read_property(cld2_detector_ce, detector, "tldHint", sizeof("tldHint") - 1, 1 TSRMLS_CC);
                                                                                                            ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /opt/cld2-php-ext/php_cld2.h:12,
                 from /opt/cld2-php-ext/cld2.cc:1:
/usr/include/php/20151012/Zend/zend_API.h:356:16: note: declared here
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zval *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^
/opt/cld2-php-ext/cld2.cc: In function ‘void zim_cld2_detector_getLanguageHint(zend_execute_data*, zval*)’:
/opt/cld2-php-ext/cld2.cc:195:122: error: too few arguments to function ‘zval* zend_read_property(zend_class_entry*, zval*, const char*, size_t, zend_bool, zval*)’
     languageHint = zend_read_property(cld2_detector_ce, detector, "languageHint", sizeof("languageHint") - 1, 1 TSRMLS_CC);
                                                                                                                          ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /opt/cld2-php-ext/php_cld2.h:12,
                 from /opt/cld2-php-ext/cld2.cc:1:
/usr/include/php/20151012/Zend/zend_API.h:356:16: note: declared here
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zval *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^
/opt/cld2-php-ext/cld2.cc: In function ‘void zim_cld2_detector_getEncodingHint(zend_execute_data*, zval*)’:
/opt/cld2-php-ext/cld2.cc:236:121: error: too few arguments to function ‘zval* zend_read_property(zend_class_entry*, zval*, const char*, size_t, zend_bool, zval*)’
     encodingHint = zend_read_property(cld2_detector_ce, detector, "encodingHint", sizeof("encodingHint") -1, 1 TSRMLS_CC);
                                                                                                                         ^
In file included from /usr/include/php/20151012/main/php.h:40:0,
                 from /opt/cld2-php-ext/php_cld2.h:12,
                 from /opt/cld2-php-ext/cld2.cc:1:
/usr/include/php/20151012/Zend/zend_API.h:356:16: note: declared here
 ZEND_API zval *zend_read_property(zend_class_entry *scope, zval *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
                ^
/opt/cld2-php-ext/cld2.cc: In function ‘void zim_cld2_language_languageName(zend_execute_data*, zval*)’:
/opt/cld2-php-ext/cld2.cc:283:9: error: ‘RETURN_STRING’ was not declared in this scope
         RETURN_STRING(CLD2::LanguageName(CLD2::UNKNOWN_LANGUAGE), 1);
         ^
/opt/cld2-php-ext/cld2.cc:287:5: error: ‘RETURN_STRING’ was not declared in this scope
     RETURN_STRING(CLD2::LanguageName(l), 1);
     ^
/opt/cld2-php-ext/cld2.cc: In function ‘void zim_cld2_language_languageCode(zend_execute_data*, zval*)’:
/opt/cld2-php-ext/cld2.cc:302:9: error: ‘RETURN_STRING’ was not declared in this scope
         RETURN_STRING(CLD2::LanguageCode(CLD2::UNKNOWN_LANGUAGE), 1);
         ^
/opt/cld2-php-ext/cld2.cc:305:5: error: ‘RETURN_STRING’ was not declared in this scope
     RETURN_STRING(CLD2::LanguageCode(l), 1);
     ^
/opt/cld2-php-ext/cld2.cc: In function ‘void zim_cld2_encoding_encodingName(zend_execute_data*, zval*)’:
/opt/cld2-php-ext/cld2.cc:347:8: error: ‘RETURN_STRING’ was not declared in this scope
        RETURN_STRING(encodingStrings[CLD2::UNKNOWN_ENCODING], 1);
        ^
/opt/cld2-php-ext/cld2.cc:350:5: error: ‘RETURN_STRING’ was not declared in this scope
     RETURN_STRING(encodingStrings[encoding], 1);
     ^
Makefile:194: recipe for target 'cld2.lo' failed
make: *** [cld2.lo] Error 1
```

**Comment by fntlnz** [comment]
There's a work in progress on this but needs more tests before merging
https://github.com/fntlnz/cld2-php-ext/pull/1/files

**Comment by stavarengo** [comment]
Thanks for the feedback @fntlnz 
I'm writing a web service that uses this extension to detect languages. It's meant to be free forever.
To my mind, it would be a easier way to start using this extension with close to zero effort.
It's a work in progress. Here is the main repository https://github.com/stavarengo/language-detection-service.
I'm also building an [PHP library](https://github.com/stavarengo/language-detection-service-php-consumer-library) that would be used to consume this API, in case people prefer not to waste any time buildind the requests to start detecting languages.

To finish, I also created a [Docker image](https://store.docker.com/community/images/stavarengo/language-detection-service) of the web service in case someone prefer to use install the API in their own servers.

If you agree we could link this repository to those I created so people get more options to start work with this extension.

**Comment by fntlnz** [comment]
Sounds like a cool plan, feel free to add the needed links and try the extension using the PHP 7 branch to see if you can catch any issues before mergig

**Comment by stavarengo** [comment]
@fntlnz, I got everything running now.   

We already have:
- An API that responds to the endpoint `/detect?t=text-to-detect` (or through POST requests). The source code of this API is [found here](https://github.com/stavarengo/language-detection-service) and this API is [live here](http://language-detection-service.stavarengo.com). See it [detecting the language of Bonjour le monde here](http://language-detection-service.stavarengo.com/detect?t=Bonjour+le+monde).
- A [Docker Image of the API](https://store.docker.com/community/images/stavarengo/language-detection-service) it self, so anyone can use its own machine to host the API (if he does not feel comfortable relying on our server).
- A [Docker Image of PHP 5.6 with the cld2-php-ext enabled](https://store.docker.com/community/images/stavarengo/cld2-php-language-detection-library). This image only do this. In fact the API Docker Image inherits from this image.
- A PHP library that comunicates with the API which allow people to just start working with the API, instead of waste time building its own way to consume the `/detect` API endpoint.

We do not have yet:
- Documentation. Would @fntlnz help me with it? :)
  - [language-detection-service-php-consumer-library](https://github.com/stavarengo/language-detection-service-php-consumer-library) needs a README file describing what it is and how to use the it.
  - [language-detection-service](https://github.com/stavarengo/language-detection-service) needs: A README file; a [well documented home page](https://github.com/stavarengo/language-detection-service/blob/master/public/site.php) describing how to use it; explaining that it is build on top of your extension and also saying that we already have an library to consume this API.

**Comment by fntlnz** [comment]
Closing since the php 7 branch was merged into develop finally.
